CREATE OR REPLACE VIEW CATEGORY_VIEW
AS
SELECT BOA.BOARD_ID AS "게시판 아이디" 
     , BOA.BOARD_NAME AS "게시판 이름"
FROM BOARD BOA JOIN BOARD_CATEGORY BC
ON BOA.BOARD_CATE_ID = BC.BOARD_CATE_ID
WHERE BC.BOARD_CATE_NAME = '커뮤니티';

SELECT *
FROM CATEGORY_VIEW;

--○ 인기글 조회
CREATE OR REPLACE VIEW ALL_HOT_POSTS_VIEW
AS
SELECT HPL.HOT_POST_LOG_ID AS "인기글 아이디"  
     , POS.POST_ID AS "게시글 아이디"
     , BOA.BOARD_NAME AS "게시판 이름"
     , PL.POST_LABEL_NAME AS "말머리 이름"
     , POS.POST_TITLE AS "게시물 제목"
     , POS.POST_CONTENT AS "게시물 내용"
     , USE.USER_NICKNAME AS "작성자"
     , POS.CREATED_DATE AS "작성일"
     , (SELECT COUNT(*)
        FROM POST_VIEW_LOG PVL
        WHERE PVL.POST_ID = POS.POST_ID) AS "조회수"
     , (SELECT COUNT(*) 
        FROM RECOMMEND REC 
        WHERE REC.POST_ID = POS.POST_ID) AS "추천수"
FROM HOT_POST_LOG HPL 
JOIN POST POS
ON HPL.POST_ID = POS.POST_ID
JOIN USER_CODE UC
ON POS.USER_CODE = UC.USER_CODE
JOIN USERS USE
ON UC.USER_CODE = USE.USER_CODE
JOIN BOARD BOA
ON POS.BOARD_ID = BOA.BOARD_ID
JOIN POST_LABEL PL
ON POS.POST_LABEL_ID = PL.POST_LABEL_ID;

SELECT *
FROM ALL_HOT_POSTS_VIEW;